export type UexCommodityRoute = {
  id_commodity: number
  id_star_system_origin: number
  id_star_system_destination: number
  id_planet_origin: number
  id_planet_destination: number
  id_orbit_origin: number
  id_orbit_destination: number
  id_terminal_origin: number
  id_terminal_destination: number
  id_faction_origin: number
  id_faction_destination: number
  code: string
  price_origin: number
  price_destination: number
  price_margin: number
  scu_origin: number
  scu_destination: number
  scu_margin: number
  volatility_origin: number
  volatility_destination: number
  status_origin: number
  status_destination: number
  investment: number
  profit: number
  score: number
  has_container_transfer_origin: boolean
  has_container_transfer_destination: boolean
  has_refuel_origin: boolean
  has_refuel_destination: boolean
  has_cargo_center_origin: boolean
  has_cargo_center_destination: boolean
  has_quantum_marker_origin: boolean
  has_quantum_marker_destination: boolean
  is_monitored_origin: boolean
  is_monitored_destination: boolean
  is_space_station_origin: boolean
  is_space_station_destination: boolean
  is_on_ground_origin: boolean
  is_on_ground_destination: boolean
  commodity_name: string
  commodity_code: string
  commodity_slug: string
  origin_star_system_name: string
  origin_planet_name: string
  origin_orbit_name: string
  origin_terminal_name: string
  origin_terminal_code: string
  origin_terminal_slug: string
  origin_faction_name: string
  destination_star_system_name: string
  destination_planet_name: string
  destination_orbit_name: string
  destination_terminal_name: string
  destination_terminal_code: string
  destination_terminal_slug: string
  destination_faction_name: string
  date_added: number
}

export type UexCommodityRanking = {
  id: number
  code: string
  slug: string
  name: string
  is_temporary: boolean
  is_illegal: boolean
  price_buy_avg: number
  price_sell_avg: number
  scu_buy_avg: number
  scu_sell_avg: number
  status_buy_avg: number
  status_sell_avg: number
  volatility_buy: number
  volatility_sell: number
  cax_score: number
  investment: number
  investment_per_scu: number
  is_average_trade_price_invalid: boolean
  profitability: number
  profitability_relative_percentage: number
  profitability_per_scu: number
  availability_buy: number
  availability_sell: number
  price_buy_minimum: number
  terminal_id_price_buy_minimum: number
  terminal_slug_price_buy_minimum: string
  price_sell_maximum: number
  terminal_id_price_sell_maximum: number
  terminal_slug_price_sell_maximum: string
}
